version: '2'
services:
  frontproxy:
    image: front:latest
    ports:
      - "8080:8080"
    networks:
      - front

  appsrv:
    image: back:latest
    ports:
      - "5000:5000"
    networks:
      - front

networks:
  front:
    driver: bridge
